Repository AY2223S1-CS2103T-T17-1/tp, pull requests merged in 2022-10, with the labels that each got.

#34 Add Position class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/position/Position.java
  src/main/java/seedu/address/model/person/position/Professor.java
  src/main/java/seedu/address/model/person/position/Student.java
  src/main/java/seedu/address/model/person/position/TeachingAssistant.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#32 change regex criteria to match {module code}-{tutorial group}
  src/main/java/seedu/address/model/tag/Tag.java
Labels: type.Task, priority.High

#31 Add remark command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#47 remove unnecessary files
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
Labels: type.Enhancement, priority.Medium, severity.VeryLow

#55 Add Assignments class and AddAssignmentsCommand
  src/main/java/seedu/address/logic/commands/AddAssignmentsCommand.java
  src/main/java/seedu/address/logic/parser/AddAssignmentsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Assignment.java
  src/main/java/seedu/address/model/person/position/Student.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#61 Add show command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/NewBookCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/commands/SwapCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/model/person/position/Position.java
  src/main/java/seedu/address/model/person/position/Professor.java
  src/main/java/seedu/address/model/person/position/Student.java
  src/main/java/seedu/address/model/person/position/TeachingAssistant.java
  src/main/java/seedu/address/ui/InfoDisplay.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/InfoDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/NewBookCommandTest.java
  src/test/java/seedu/address/logic/commands/SwapCommandTest.java
Labels: priority.High

#70 Edit UserGuide.md and DeveloperGuide.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FilterDiagram1.png
  docs/images/FilterDiagram2.png
  docs/images/FilterDiagram3.png
  docs/images/FilterDiagram4.png
  docs/images/FilterDiagram5.png
  docs/images/FilterDiagram6.png
  docs/images/FilterDiagram7.png
Labels: priority.High

#74 Update DeveloperGuide.md with implementation of ShowCommand
  docs/DeveloperGuide.md
  docs/diagrams/ShowDiagram1.puml
  docs/diagrams/ShowDiagram2.puml
  docs/diagrams/ShowDiagram3.puml
  docs/diagrams/ShowSequenceDiagram.puml
  docs/images/ShowDiagram1.png
  docs/images/ShowDiagram2.png
  docs/images/ShowDiagram3.png
  docs/images/ShowSequenceDiagram.png
Labels: priority.High

#89 UI overhaul
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoDisplay.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#84 Improve Add Assignments feature
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/commands/AddAssignmentsCommand.java
  src/main/java/seedu/address/logic/commands/AttendanceCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/position/Position.java
  src/main/java/seedu/address/model/person/position/Professor.java
  src/main/java/seedu/address/model/person/position/Student.java
  src/main/java/seedu/address/model/person/position/TeachingAssistant.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#83 Add rename function
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/RenameCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RenameCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/NewBookCommandTest.java
  src/test/java/seedu/address/logic/commands/SwapCommandTest.java
Labels: type.Enhancement, priority.Medium

#94 Debug Roles command
  src/main/java/seedu/address/logic/commands/RolesCommand.java
Labels: type.Bug
